name        'Khal3d-mailcatcher'
version     '0.1.0'
summary     'Puppet module to install Mailcatcher.'
description 'Puppet module to install Mailcatcher.'
license     'MIT'
author      'Khaled Attia'
